import backend.model.Meal;
import java.sql.Timestamp;

rule "AddDateToMeal"
    agenda-group "eatenMeals"
    when
        $m: Meal(mealTime == null)
    then
        $m.setMealTime(new Timestamp(System.currentTimeMillis()));
end

rule "MealCounterUpdate"
    agenda-group "eatenMeals"
    when
        $m: Meal($recipe: recipe)
    then
        $recipe.setTimesEaten($recipe.getTimesEaten() + 1);
end