import backend.model.Meal;
import backend.model.Recipe;
import java.sql.Timestamp;

global Long maxTimesEaten;

rule "AddDateToMeal"
    agenda-group "eatenMeals"
    when
        $m: Meal(mealTime == null)
    then
        $m.setMealTime(new Timestamp(System.currentTimeMillis()));
end

rule "RecipeEatenCounterUpdate"
    agenda-group "eatenMeals"
    when
        $m: Meal($recipe: recipe)
    then
        $recipe.setTimesEaten($recipe.getTimesEaten() + 1);
end

rule "Calculate rating" salience -1
    agenda-group "eatenMeals"
    when
        $m: Meal($recipe: recipe)
    then
        $recipe.setRating($recipe.getTimesEaten()/maxTimesEaten);
end