import backend.model.UserModel;
import backend.model.enumeration.*;

// MANTAIN ---------------------------------------------

rule "CalculateUserCalorieThreshold_MANTAIN_female"
    agenda-group "calorieCalculator"
    when
        $u: UserModel($age: age, $weight: weight, $height: height, weightGoal == WeightGoal.MAINTAIN, gender == Gender.FEMALE)
    then
        $u.setCaloriesThreshold((655 + 9.6 * $weight + 1.8 * $height - 4.7 * $age)*1.5);
end

rule "CalculateUserCalorieThreshold_MANTAIN_male"
    agenda-group "calorieCalculator"
    when
        $u: UserModel($age: age, $weight: weight, $height: height, weightGoal == WeightGoal.MAINTAIN, gender == Gender.MALE)
    then
        $u.setCaloriesThreshold((66 + 13.7 * $weight + 5 * $height - 6.8 * $age)*1.25);
end

// GAIN ---------------------------------------------

rule "CalculateUserCalorieThreshold_GAIN_female"
    agenda-group "calorieCalculator"
    when
        $u: UserModel($age: age, $weight: weight, $height: height, weightGoal == WeightGoal.GAIN, gender == Gender.FEMALE)
    then
        $u.setCaloriesThreshold((655 + 9.6 * $weight + 1.8 * $height - 4.7 * $age)*1.5 + 200);
end

rule "CalculateUserCalorieThreshold_GAIN_male"
    agenda-group "calorieCalculator"
    when
        $u: UserModel($age: age, $weight: weight, $height: height, weightGoal == WeightGoal.GAIN, gender == Gender.MALE)
    then
        $u.setCaloriesThreshold((66 + 13.7 * $weight + 5 * $height - 6.8 * $age)*1.25 + 200);
end

// LOSE ---------------------------------------------

rule "CalculateUserCalorieThreshold_LOSE_female"
    agenda-group "calorieCalculator"
    when
        $u: UserModel($age: age, $weight: weight, $height: height, weightGoal == WeightGoal.LOSE, gender == Gender.FEMALE)
    then
        $u.setCaloriesThreshold((655 + 9.6 * $weight + 1.8 * $height - 4.7 * $age)*1.5 - 200);
end

rule "CalculateUserCalorieThreshold_LOSE_male"
    agenda-group "calorieCalculator"
    when
        $u: UserModel($age: age, $weight: weight, $height: height, weightGoal == WeightGoal.LOSE, gender == Gender.MALE)
    then
        $u.setCaloriesThreshold((66 + 13.7 * $weight + 5 * $height - 6.8 * $age)*1.25 - 200);
end

rule "CalculateMacrosBasedOnCalorieThreshold" salience -1
    agenda-group "calorieCalculator"
    when
        $u: UserModel($macros: macros, $calorieThreshold: caloriesThreshold)
    then
        $u.getMacros().setCalories($u.getCaloriesThreshold());
        $u.getMacros().setProtein($u.getCaloriesThreshold()*0.5/4);
        $u.getMacros().setCarbs($u.getCaloriesThreshold()*0.3/4);
        $u.getMacros().setCalories($u.getCaloriesThreshold()*0.2/9);
end